Repository mpstinnett/Computer-Science-Project-F22, pull requests merged in 2022-10, with the labels that each got.

#37 Refactor Add Course
  resources/CourseList.json
  src/main/java/com/group12/degreeaudit/Administration/CourseList.java
  src/main/java/com/group12/degreeaudit/Administration/JSONCourse.java
Labels: Feature, Backend

#41 Administration update course + bugfixes
  src/main/java/com/group12/degreeaudit/Administration/CourseList.java
  src/main/java/com/group12/degreeaudit/Administration/JSONCourse.java
  src/main/java/com/group12/degreeaudit/DegreeAudit.java
Labels: bug, enhancement, Feature, Backend

#42 Add courses
  resources/CourseList.json
  src/main/java/com/group12/degreeaudit/Administration/CourseList.java
  src/main/java/com/group12/degreeaudit/DegreeAudit.java
  src/main/java/com/group12/degreeaudit/Student.java
Labels: enhancement, Backend

#43 Administration - Degree Track Overhall
  resources/DegreeList.json
  src/main/java/com/group12/degreeaudit/Administration/CourseList.java
  src/main/java/com/group12/degreeaudit/Administration/DegreeList.java
  src/main/java/com/group12/degreeaudit/Administration/JSONDegree.java
  src/main/java/com/group12/degreeaudit/DegreeAudit.java
Labels: Feature, Backend

#58 Finished Overrule
  resources/CourseList.json
  src/main/java/com/group12/degreeaudit/Administration/CourseList.java
  src/main/java/com/group12/degreeaudit/Administration/DegreeList.java
  src/main/java/com/group12/degreeaudit/Administration/DegreePlanner.java
  src/main/java/com/group12/degreeaudit/Administration/JSONDegree.java
  src/main/java/com/group12/degreeaudit/DegreeAudit.java
  src/main/java/com/group12/degreeaudit/Student.java
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: Feature, Backend

#59 Refactor Add Course
  resources/CourseList.json
  src/main/java/com/group12/degreeaudit/Administration/DegreePlanner.java
  src/main/java/com/group12/degreeaudit/DegreeAudit.java
Labels: enhancement, Backend
